# theme: jekyll-theme-minimal
title: Welcome to Stefano's GitHub page
description: Site under construnction
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
logo: /assets/images/logo.png
social:
  instagram: "https://www.instagram.com/stefano.ronchini"
  linkedin: "https://www.linkedin.com/in/stefano-ronchini-0370a9111"
personal:
  mail: "stefano.ronchini93@gmail.com"
